# .github/workflows/fetch-repos.yml
name: Fetch GitHub Repos for Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch raw repos list
        env:
          GITHUB_TOKEN: ${{ secrets.GH_FETCH_TOKEN }}
        run: |
          curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/users/MadeInShineA/repos?per_page=100&sort=updated" \
            > repos-raw.json

      - name: Validate JSON
        run: jq . repos-raw.json > /dev/null

      - name: Inline languages into repos.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_FETCH_TOKEN }}
        run: |
          # Read each repo in compact form, fetch its languages, emit compact JSON array with -c
          while IFS= read -r repo; do
            url=$(jq -r '.languages_url' <<< "$repo")
            raw=$(curl -s \
              -H "Authorization: token $GITHUB_TOKEN" \
              "$url")
            # -c gives you ["C","JavaScript",...] on one line
            langs=$(jq -c 'keys' <<< "$raw")
            echo "$repo" | jq --argjson languages "$langs" '. + { languages }'
          done < <(jq -c '.[]' repos-raw.json) \
            > repos.json

      - name: Commit updated repos.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "chore: update repos.json"
          add: repos.json
