# .github/workflows/fetch-repos.yml
name: Fetch GitHub Repos for Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch & flatten repos.json (with commits)
        env:
          GH_TOKEN: ${{ secrets.GH_FETCH_TOKEN }}
        run: |
          gh api graphql \
            -f query='
            query($owner: String!, $perPage: Int!, $firstLangs: Int!) {
              user(login: $owner) {
                repositories(first: $perPage, orderBy: {field: UPDATED_AT, direction: DESC}) {
                  nodes {
                    name
                    description
                    url
                    stargazerCount
                    updatedAt
                    defaultBranchRef {
                      target {
                        ... on Commit {
                          history {
                            totalCount
                          }
                        }
                      }
                    }
                    languages(first: $firstLangs) {
                      nodes { name }
                    }
                  }
                }
              }
            }' \
            -f variables='{"owner":"MadeInShineA","perPage":100,"firstLangs":10}' \
            --jq '.data.user.repositories.nodes
              | map({
                  owner: { login: "MadeInShineA" },
                  name,
                  description,
                  url,
                  stargazerCount,
                  updatedAt,
                  commits: .defaultBranchRef.target.history.totalCount,
                  languages: [.languages.nodes[].name]
                })' \
          > repos.json

      - name: Commit updated repos.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "chore: update repos.json (include commits)"
          add: repos.json
